name: "Test setup-nativescript #7"

on: [push]

jobs:
  build_app:
    name: Build App on Node.js ${{ matrix.node-version }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        node-version: [12]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Prepare ( checkout code and setup build environment )
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install deps and auth in private npm registry
      - name: Install npm-ci-login and angular-cli
        run: |
          yarn global add npm-ci-login @angular/cli@8.3.24
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - uses: hrueger/setup-nativescript@v1.1.0
        with:
          nativescript-version: "7.0.10"